### ISSUE TITLE
unable start gsn-relay - unexpected param HOST=g*.****.com

### ISSUE THREAD

**Issue by rmlcu** [opengsn/gsn#921]
**unable start gsn-relay**
`unexpected param HOST=g*.****.com`

**Steps To Reproduce**
- download stable release gsn-2.2.5
- follow guide steps till "rdc local config" and "rdc local up -d"

**Console Logs and/or Screenshots**
"rdc local config" output:
```
services:
  gsn1:
    environment:
      config: /app/config/gsn-relay-config.json
      port: 80
      relayHubId: hub
      url: https://relay.hostname.com/gsn1
      workdir: /app/data
    image: opengsn/jsrelay:2.2.5
    restart: on-failure
    volumes:
    - /home/username/gsn-2.2.5/dockers/relaydc/gsndata/gsn1:/app/data:rw
    - /home/username/gsn-2.2.5/dockers/relaydc/gsndata/manager:/app/data/manager:rw
    - /home/username/gsn-2.2.5/dockers/relaydc/config:/app/config:ro
  https-portal:
    environment:
      DOMAINS: relay.hostname.com -> http://router
      STAGE: staging
    image: steveltn/https-portal:1
    ports:
    - 443:443/tcp
    - 80:80/tcp
    restart: always
  router:
    command:
    - gsn1
    container_name: router
    image: opengsn/prefixrouter
    ports:
    - 8080:80/tcp
    restart: always
version: '3.0'
```
sudo docker ps:
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED              STATUS                          PORTS                                                                      NAMES
6db97dbf0391   opengsn/jsrelay:2.2.5   "docker-entrypoint.s…"   About a minute ago   Restarting (1) 10 seconds ago                                                                              default_gsn1_1
3942da444c08   steveltn/https-portal:1        "/init"                  About a minute ago   Up About a minute               0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   default_https-portal_1
91f76bb385a8   opengsn/prefixrouter           "/docker-entrypoint.…"   About a minute ago   Up About a minute               0.0.0.0:8080->80/tcp, :::8080->80/tcp                                      router
```

sudo docker logs 6db97dbf0391:
```
Starting GSN Relay Server process...

Parsing server config...

Using config file /app/config/gsn-relay-config.json
Initial configuration: {
  HOST: 'relay.hostname.com',
  baseRelayFee: 0,
  pctRelayFee: 70,
  versionRegistryAddress: '0x97B6ebd38f2000B6E446DE24D9805606b882A1C5',
  ownerAddress: '0x8***3',
  gasPriceFactor: 1,
  ethereumNodeUrl: 'https://mainnet.infura.io/v3/***'
}
unexpected param HOST=relay.hostname.com
```

of course username and hostname changed for privacy concerns
